apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus-app5"
  annotations:
    argocd/app-name: my-quarkus-app5-dev
    backstage.io/kubernetes-id: my-quarkus-app5
    backstage.io/kubernetes-namespace: my-quarkus-app5-dev
    janus-idp.io/tekton-enabled : 'true'
    github.com/project-slug: janus-idp-demo/backstage-sample-quarkus-app5
    quay.io/repository-slug: "/my-quarkus-app5"
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-l2nrz.l2nrz.sandbox1604.opentlc.com/#https://github.com/janus-idp-demo/backstage-sample-quarkus-app5?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-l2nrz.l2nrz.sandbox1604.opentlc.com/#https://github.com/janus-idp-demo/backstage-sample-quarkus-app5?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "group:default/jayfray"
  providesApis:
    - "my-quarkus-app5"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "my-quarkus-app5"
spec:
  type: openapi
  lifecycle: production
  owner: "group:default/jayfray"
  definition:
    $text: ./openapi.yaml
